export const INFO       = Symbol('Info')
export const DATASTORE  = Symbol('DataStore')
export const EVENT      = Symbol('Event')
export const COMMAND    = Symbol('Command')
export const APPSTATE   = Symbol('Application State')
export const ERROR      = Symbol('ERROR')
